site_name: Slim Framework
pages:
- Home: index.md
- Get Started:
  - Installation: start/installation.md
  - Web Servers: start/web-servers.md
- Concepts:
  - Objects: concepts/objects.md
  - Dependency Injection: concepts/di.md
  - Middleware: concepts/middleware.md
  - PSR-7: concepts/value-objects.md
- Objects:
  - Request: objects/request.md
  - Response: objects/response.md
  - Router: objects/router.md
  - Environment: objects/environment.md
- Features:
  - Views and Templates: features/templates.html
- Caching: caching.md
- Error Handling:
  - 500 Server Error: handlers/error.md
  - 404 Not Found: handlers/not-found.md
  - 405 Not Allowed: handlers/not-allowed.md
- Contributors:
  - Branching Strategy: contributors/strategy.md
theme: readthedocs
markdown_extensions: [markdown.extensions.extra]
